#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${1:-$ROOT_DIR/.env}"

mkdir -p "$(dirname "$OUTPUT_FILE")"

: "${COMPOSE_PROJECT_NAME:=starter}"
: "${DEPLOY_ENV:=dev}"
: "${BACK_IMAGE:=ghcr.io/example/starter-back}"
: "${BACK_IMAGE_TAG:=dev}"
: "${FRONT_IMAGE:=ghcr.io/example/starter-front}"
: "${FRONT_IMAGE_TAG:=dev}"
: "${BACK_BUILD_CONTEXT:=../starter_back}"
: "${BACK_DOCKERFILE:=Dockerfile}"
: "${FRONT_BUILD_CONTEXT:=../starter_front}"
: "${FRONT_DOCKERFILE:=Dockerfile}"
: "${MYSQL_VERSION:=8.4.9}"
: "${REDIS_VERSION:=8.6.3-alpine}"
: "${NGINX_VERSION:=1.30.0-alpine}"
: "${MERCURE_VERSION:=v0.23.5}"
: "${MAILPIT_VERSION:=latest}"
: "${GRAFANA_VERSION:=13.0.1}"
: "${PROMETHEUS_VERSION:=v3.11.3}"
: "${LOKI_VERSION:=3.7.1}"
: "${ALLOY_VERSION:=v1.16.1}"
: "${CADVISOR_VERSION:=v0.55.1}"
: "${MYSQL_DATABASE:=app}"
: "${MYSQL_USER:=app}"
: "${APP_DOMAIN:=app.localhost}"
: "${HOST_HTTP_PORT:=80}"
: "${HOST_HTTPS_PORT:=443}"
: "${MAILPIT_SMTP_PORT:=1025}"
: "${MAILPIT_HTTP_PORT:=8025}"
: "${TLS_CERT_PATH:=/etc/nginx/certs/dev/fullchain.pem}"
: "${TLS_KEY_PATH:=/etc/nginx/certs/dev/privkey.pem}"
: "${BACK_HTTP_PORT:=8080}"
: "${BACK_HEALTH_PATH:=/api/health}"
: "${FRONT_HTTP_PORT:=3000}"
: "${MIGRATION_COMMAND:=php bin/console doctrine:migrations:migrate --no-interaction}"
: "${WORKER_DEFAULT_COMMAND:=php bin/console messenger:consume async --time-limit=3600 --memory-limit=256M}"
: "${WORKER_MAIL_COMMAND:=php bin/console messenger:consume async_mail --time-limit=3600 --memory-limit=256M}"
: "${WORKER_OUTBOX_COMMAND:=php bin/console messenger:consume async_outbox --time-limit=3600 --memory-limit=256M}"
: "${SCHEDULER_COMMAND:=/usr/local/bin/scheduler-loop.sh}"
: "${SCHEDULER_TICK_COMMAND:=php bin/console app:schedule:run}"
: "${MERCURE_CORS_ALLOWED_ORIGINS:=https://${APP_DOMAIN}}"
: "${MERCURE_PUBLISH_ALLOWED_ORIGINS:=https://${APP_DOMAIN}}"
: "${ENABLE_OBSERVABILITY:=0}"
: "${GRAFANA_AUTH_BASIC_REALM:=off}"
: "${PROMETHEUS_RETENTION:=7d}"
: "${LOKI_RETENTION:=168h}"
: "${ENABLE_MEDIA_EDGE:=0}"
: "${MEDIA_EDGE_BASE_URL:=}"

COMPOSE_PROFILES=""
if [ "${ENABLE_OBSERVABILITY}" = "1" ]; then
  COMPOSE_PROFILES="observability"
fi

cat > "$OUTPUT_FILE" <<EOF
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
COMPOSE_PROFILES=${COMPOSE_PROFILES}
DEPLOY_ENV=${DEPLOY_ENV}
BACK_IMAGE=${BACK_IMAGE}
BACK_IMAGE_TAG=${BACK_IMAGE_TAG}
FRONT_IMAGE=${FRONT_IMAGE}
FRONT_IMAGE_TAG=${FRONT_IMAGE_TAG}
BACK_BUILD_CONTEXT=${BACK_BUILD_CONTEXT}
BACK_DOCKERFILE=${BACK_DOCKERFILE}
FRONT_BUILD_CONTEXT=${FRONT_BUILD_CONTEXT}
FRONT_DOCKERFILE=${FRONT_DOCKERFILE}
MYSQL_VERSION=${MYSQL_VERSION}
REDIS_VERSION=${REDIS_VERSION}
NGINX_VERSION=${NGINX_VERSION}
MERCURE_VERSION=${MERCURE_VERSION}
MAILPIT_VERSION=${MAILPIT_VERSION}
GRAFANA_VERSION=${GRAFANA_VERSION}
PROMETHEUS_VERSION=${PROMETHEUS_VERSION}
LOKI_VERSION=${LOKI_VERSION}
ALLOY_VERSION=${ALLOY_VERSION}
CADVISOR_VERSION=${CADVISOR_VERSION}
MYSQL_DATABASE=${MYSQL_DATABASE}
MYSQL_USER=${MYSQL_USER}
APP_DOMAIN=${APP_DOMAIN}
HOST_HTTP_PORT=${HOST_HTTP_PORT}
HOST_HTTPS_PORT=${HOST_HTTPS_PORT}
MAILPIT_SMTP_PORT=${MAILPIT_SMTP_PORT}
MAILPIT_HTTP_PORT=${MAILPIT_HTTP_PORT}
TLS_CERT_PATH=${TLS_CERT_PATH}
TLS_KEY_PATH=${TLS_KEY_PATH}
BACK_HTTP_PORT=${BACK_HTTP_PORT}
BACK_HEALTH_PATH=${BACK_HEALTH_PATH}
FRONT_HTTP_PORT=${FRONT_HTTP_PORT}
MIGRATION_COMMAND=${MIGRATION_COMMAND}
WORKER_DEFAULT_COMMAND=${WORKER_DEFAULT_COMMAND}
WORKER_MAIL_COMMAND=${WORKER_MAIL_COMMAND}
WORKER_OUTBOX_COMMAND=${WORKER_OUTBOX_COMMAND}
SCHEDULER_COMMAND=${SCHEDULER_COMMAND}
SCHEDULER_TICK_COMMAND=${SCHEDULER_TICK_COMMAND}
MERCURE_CORS_ALLOWED_ORIGINS=${MERCURE_CORS_ALLOWED_ORIGINS}
MERCURE_PUBLISH_ALLOWED_ORIGINS=${MERCURE_PUBLISH_ALLOWED_ORIGINS}
ENABLE_OBSERVABILITY=${ENABLE_OBSERVABILITY}
GRAFANA_AUTH_BASIC_REALM=${GRAFANA_AUTH_BASIC_REALM}
PROMETHEUS_RETENTION=${PROMETHEUS_RETENTION}
LOKI_RETENTION=${LOKI_RETENTION}
ENABLE_MEDIA_EDGE=${ENABLE_MEDIA_EDGE}
MEDIA_EDGE_BASE_URL=${MEDIA_EDGE_BASE_URL}
EOF

echo "Compose env written to $OUTPUT_FILE"
