#!/usr/bin/env bash
set -euo pipefail

TARGET_ENV="${1:-dev}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/env/.env.${TARGET_ENV}"

mkdir -p "$ROOT_DIR/env"

: "${APP_DOMAIN:=app.local}"
: "${APP_ENV:=prod}"
: "${APP_DEBUG:=0}"
: "${APP_SECRET:=change-me}"
: "${MYSQL_DATABASE:=my_app}"
: "${MYSQL_USER:=my_app}"
: "${MYSQL_PASSWORD:=change-me}"
: "${MYSQL_ROOT_PASSWORD:=change-me}"
: "${REDIS_URL:=redis://redis:6379}"
: "${MESSENGER_TRANSPORT_DSN:=redis://redis:6379/messages_async}"
: "${MESSENGER_MAIL_TRANSPORT_DSN:=redis://redis:6379/messages_mail}"
: "${MESSENGER_OUTBOX_TRANSPORT_DSN:=redis://redis:6379/messages_outbox}"
: "${MESSENGER_FAILED_TRANSPORT_DSN:=redis://redis:6379/messages_failed}"
: "${MERCURE_JWT_SECRET:=dev-mercure-jwt-secret-32-bytes-minimum}"
: "${MAILER_DSN:=smtp://mailpit:1025}"
: "${MAILER_FROM:=no-reply@example.test}"
: "${APP_FRONT_BASE_URL:=https://${APP_DOMAIN}}"
: "${DEFAULT_URI:=https://${APP_DOMAIN}}"
: "${MEDIA_EDGE_BASE_URL:=}"
: "${BACK_HTTP_PORT:=8080}"
: "${INTERNAL_API_BASE_URL:=http://back:${BACK_HTTP_PORT}/api}"
: "${API_BASE_URL:=${INTERNAL_API_BASE_URL}}"
: "${NEXT_PUBLIC_APP_NAME:=My App}"
: "${NEXT_PUBLIC_MEDIA_BASE_URL:=}"
: "${NEXT_PUBLIC_MEDIA_UPLOAD_BASE_URL:=}"
: "${NEXT_PUBLIC_APP_URL:=https://${APP_DOMAIN}}"
: "${NEXT_PUBLIC_MERCURE_URL:=https://${APP_DOMAIN}/.well-known/mercure}"
: "${NEXT_PUBLIC_MERCURE_DISABLED:=false}"
: "${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:=}"
: "${NEXT_PUBLIC_VAPID_PUBLIC_KEY:=}"
: "${B2_ENDPOINT:=}"
: "${B2_BUCKET:=}"
: "${B2_PREFIX:=}"
: "${JWT_SECRET_KEY:=%kernel.project_dir%/config/jwt/private.pem}"
: "${JWT_PUBLIC_KEY:=%kernel.project_dir%/config/jwt/public.pem}"
: "${JWT_PASSPHRASE:=change-me}"
: "${JWT_PRIVATE_KEY_PEM:=}"
: "${JWT_PUBLIC_KEY_PEM:=}"
: "${STRIPE_SECRET_KEY:=}"
: "${STRIPE_WEBHOOK_SECRET:=}"
: "${GRAFANA_ADMIN_USER:=admin}"
: "${GRAFANA_ADMIN_PASSWORD:=change-me-observe}"
: "${GRAFANA_SECRET_KEY:=change-me-observe}"

if [ -z "${NEXT_PUBLIC_MEDIA_BASE_URL}" ]; then
  NEXT_PUBLIC_MEDIA_BASE_URL="${MEDIA_EDGE_BASE_URL:-https://${APP_DOMAIN}}"
fi

if [ -z "${NEXT_PUBLIC_MEDIA_UPLOAD_BASE_URL}" ]; then
  NEXT_PUBLIC_MEDIA_UPLOAD_BASE_URL="https://${APP_DOMAIN}"
fi

escape_env_file_value() {
  local value="$1"
  value="${value//$'\n'/\\n}"
  printf '%s' "$value"
}

JWT_PRIVATE_KEY_PEM="$(escape_env_file_value "$JWT_PRIVATE_KEY_PEM")"
JWT_PUBLIC_KEY_PEM="$(escape_env_file_value "$JWT_PUBLIC_KEY_PEM")"

cat > "$OUTPUT_FILE" <<EOF
APP_ENV=${APP_ENV}
APP_DEBUG=${APP_DEBUG}
APP_SECRET=${APP_SECRET}
APP_FRONT_BASE_URL=${APP_FRONT_BASE_URL}
DEFAULT_URI=${DEFAULT_URI}

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_PASSWORD=${MYSQL_PASSWORD}
MYSQL_DATABASE=${MYSQL_DATABASE}
MYSQL_USER=${MYSQL_USER}
DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}

REDIS_URL=${REDIS_URL}
MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN}
MESSENGER_MAIL_TRANSPORT_DSN=${MESSENGER_MAIL_TRANSPORT_DSN}
MESSENGER_OUTBOX_TRANSPORT_DSN=${MESSENGER_OUTBOX_TRANSPORT_DSN}
MESSENGER_FAILED_TRANSPORT_DSN=${MESSENGER_FAILED_TRANSPORT_DSN}

MERCURE_JWT_SECRET=${MERCURE_JWT_SECRET}
MERCURE_URL=http://mercure/.well-known/mercure
MERCURE_PUBLIC_URL=https://${APP_DOMAIN}/.well-known/mercure

TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR
CORS_ALLOW_ORIGIN=https://${APP_DOMAIN}

API_BASE_URL=${API_BASE_URL}
NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
NEXT_PUBLIC_API_URL=https://${APP_DOMAIN}/api
NEXT_PUBLIC_MERCURE_URL=${NEXT_PUBLIC_MERCURE_URL}
NEXT_PUBLIC_MERCURE_DISABLED=${NEXT_PUBLIC_MERCURE_DISABLED}
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
NEXT_PUBLIC_MEDIA_BASE_URL=${NEXT_PUBLIC_MEDIA_BASE_URL}
NEXT_PUBLIC_MEDIA_UPLOAD_BASE_URL=${NEXT_PUBLIC_MEDIA_UPLOAD_BASE_URL}
NEXT_PUBLIC_VAPID_PUBLIC_KEY=${NEXT_PUBLIC_VAPID_PUBLIC_KEY}

MAILER_DSN=${MAILER_DSN}
MAILER_FROM=${MAILER_FROM}
MEDIA_EDGE_BASE_URL=${MEDIA_EDGE_BASE_URL}
B2_ENDPOINT=${B2_ENDPOINT}
B2_BUCKET=${B2_BUCKET}
B2_PREFIX=${B2_PREFIX}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
JWT_PASSPHRASE=${JWT_PASSPHRASE}
JWT_PRIVATE_KEY_PEM=${JWT_PRIVATE_KEY_PEM}
JWT_PUBLIC_KEY_PEM=${JWT_PUBLIC_KEY_PEM}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}


GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER}
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
GRAFANA_SECRET_KEY=${GRAFANA_SECRET_KEY}
EOF

echo "Runtime env written to $OUTPUT_FILE"
